backend = "resized"
color_space = "labmixed"

# threshold = 10

palette = "dark16"
check_contrast = true
saturate = 100

[templates]
hypr.template = "colors-hyprland" 
hypr.target = "~/.config/hypr/hypr-colors.conf"

kitty.template = "colors-kitty"
kitty.target = "~/.config/kitty/kitty.conf"

eww.template = "colors.scss"
eww.target = "~/.config/eww/colors.scss"

# Credit: https://github.com/dlasagno/vscode-wal-theme/issues/23
wal.template = "pywal-colors"
wal.target = "~/.cache/wal/colors"