backend = "resized"
color_space = "lab"

threshold = 20

palette = "dark"

[templates]
hypr.template = "colors-hyprland" 
hypr.target = "~/.config/hypr/hypr-colors.conf"

kitty.template = "colors-kitty"
kitty.target = "~/.config/kitty/kitty-colors.conf"