backend = "resized"
color_space = "labmixed"

threshold = 10

palette = "dark"

[templates]
hypr.template = "colors-hyprland" 
hypr.target = "~/.config/hypr/hypr-colors.conf"

kitty.template = "colors-kitty"
kitty.target = "~/.config/kitty/kitty.conf"